# Estilo base del prompt
format = """
[ğŸ§](bold green)$battery$hostname$directory$git_branch$git_status$nodejs$package
$character
"""


[hostname]
ssh_only = false
format = "[$hostname]($style) " # El espacio al final ayuda a la legibilidad
style = "bold dimmed white"      # Puedes cambiar el color aquÃ­
disabled = false                 # AsegÃºrate de que no estÃ© desactivado


[custom.min_path]
command = "echo $STARSHIP_MIN_PATH"
style = "bold purple"
format = "ğŸ“ [$output]($style) "

[custom.dir_segments]
command = "echo $STARSHIP_DIR_SEGMENTS"
style = "bold purple"
format = "ğŸ“ [$output]($style) "


#$custom.battery_alert

# SÃ­mbolo de entrada
[character]
success_symbol = "[âœ](bold #7700F0)"
error_symbol = "[âœ—](bold red)"
vicmd_symbol = "[V](bold green)"

# Directorio actual
[directory]
# style = "bold purple"
truncation_length = 2
truncate_to_repo = true
style = "bold green"
format = "[$path]($style) "
truncation_symbol = 'â€¦/'

# Git branch
[git_branch]
symbol = "ğŸŒ¿ "
style = "bold #7700F0"

# Git status
[git_status]
style = "bold purple"
conflicted = "âš”ï¸ "
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
untracked = "ğŸŒ€ "
stashed = "ğŸ“¦ "
modified = "ğŸ› ï¸ "
staged = "ğŸŸ© "
renamed = "ğŸ”€ "
deleted = "ğŸ—‘ï¸ "

# Node.js
[nodejs]
symbol = "ğŸŸ¢ "
style = "bold green"

# Package (NPM)
[package]
symbol = "ğŸ“¦ "
style = "bold yellow"

# BaterÃ­a
[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡"
discharging_symbol = "ğŸ”»"


[[battery.display]]
threshold = 15
style = "bold red"
discharging_symbol = "ğŸª«"
charging_symbol = "ğŸª«"

[[battery.display]]
threshold = 100
style = "bold #7700F0"

# Alerta visual si baterÃ­a baja
# [custom.battery_alert]
# command = "echo 'ğŸ§'"
# # when = "env.STARSHIP_BATTERY_ALERT == 'low'"
# style = "bold red"
# format = "$output"

